server:
  port: 3000
  debugPort: 8080
  production: false
  handlerTimeout: 15s

market:
  psx:
    baseurl: https://dps.psx.com.pk
    scraperurl:
      indices: /indices
      company: /company
      reports: /company/reports
      symbols: /symbols
    timeseriesurl:
      eod: /timeseries/eod/
      intraday: /timeseries/int/
database:
  host: localhost
  port: 3306
  user: root
  password: root
  name: raas_stocks
  sslmode: disable
  net: tcp
  timeout: 5s
